# Generated by Django 5.2 on 2025-04-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
